version: '3.9'
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react-application
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    restart: always